"""initial_schema

Revision ID: 1a11599a9554
Revises: 
Create Date: 2026-05-02 16:05:09.029937

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a11599a9554'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_slug'), 'categorias', ['slug'], unique=True)
    op.create_table('etiquetas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etiquetas_slug'), 'etiquetas', ['slug'], unique=True)
    op.create_table('organizaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rfc', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('dominio_corporativo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'inactiva', name='estadoorganizacion'), nullable=False),
    sa.Column('email_contacto', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telefono_contacto', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('plan_de_cursos', sa.Text(), nullable=True),
    sa.Column('fecha_compra', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('rol', sa.Enum('estudiante', 'instructor', 'supervisor', 'usuario_control', 'administrador', name='rolusuario'), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'suspendido', 'pendiente_activacion', name='estadousuario'), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('telefono_e164', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False),
    sa.Column('notif_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_reset_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('password_reset_expira', sa.DateTime(), nullable=True),
    sa.Column('token_activacion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('token_activacion_expira', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('cursos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('instructor_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('borrador', 'revision', 'publicado', 'archivado', name='estadocurso'), nullable=False),
    sa.Column('marca', sa.String(length=20), server_default='ram', nullable=False),
    sa.Column('duracion_seg', sa.Integer(), nullable=False),
    sa.Column('calificacion_prom', sa.Float(), nullable=False),
    sa.Column('total_resenas', sa.Integer(), nullable=False),
    sa.Column('es_gratis', sa.Boolean(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), server_default='MXN', nullable=False),
    sa.Column('destacado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('portada_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('bunny_library_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('bunny_collection_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('publicado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_slug'), 'cursos', ['slug'], unique=True)
    op.create_table('eventos_sistema',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('categoria', sa.Enum('auth', 'crud', 'admin', 'sistema', name='categoriaevento'), nullable=False),
    sa.Column('accion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entidad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('entidad_id', sa.Uuid(), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('canal', sa.Enum('email', 'whatsapp', 'push', 'inapp', name='canalnotificacion'), nullable=False),
    sa.Column('tipo', sa.Enum('inscripcion', 'certificado', 'solicitud', 'sistema', 'invitacion', name='tiponotificacion'), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('cuerpo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'enviada', 'fallida', 'leida', name='estadonotificacion'), nullable=False),
    sa.Column('proveedor', sa.Enum('twilio', 'email', 'internal', name='proveedornotificacion'), nullable=True),
    sa.Column('proveedor_message_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.Column('leido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('revocado_en', sa.DateTime(), nullable=True),
    sa.Column('reemplazado_por_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_creacion', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_table('solicitudes_curso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizacion_id', sa.Uuid(), nullable=False),
    sa.Column('solicitante_id', sa.Uuid(), nullable=False),
    sa.Column('titulo_solicitud', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('abierta', 'en_revision', 'aprobada', 'rechazada', 'cerrada', name='estadosolicitud'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitante_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_organizacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizacion_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('rol_org', sa.Enum('miembro', 'admin_org', name='rolorganizacion'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'usuario_id')
    )
    op.create_table('calificaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('estrellas', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('comentario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('publica', 'oculta', 'pendiente', name='estadocalificacion'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'curso_id')
    )
    op.create_table('comentarios_solicitud',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('solicitud_id', sa.Uuid(), nullable=False),
    sa.Column('autor_id', sa.Uuid(), nullable=False),
    sa.Column('comentario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_curso.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso_etiquetas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('etiqueta_id', sa.Uuid(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiquetas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curso_id', 'etiqueta_id')
    )
    op.create_table('inscripciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'finalizada', 'cancelado', name='estadoinscripcion'), nullable=False),
    sa.Column('inscrito_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acceso_en', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'curso_id')
    )
    op.create_table('invitaciones_curso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('usado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Uuid(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['user.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitaciones_curso_curso_id'), 'invitaciones_curso', ['curso_id'], unique=False)
    op.create_index(op.f('ix_invitaciones_curso_email'), 'invitaciones_curso', ['email'], unique=False)
    op.create_index(op.f('ix_invitaciones_curso_token_hash'), 'invitaciones_curso', ['token_hash'], unique=True)
    op.create_table('licencias_curso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizacion_id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('cupos_total', sa.Integer(), nullable=False),
    sa.Column('cupos_usados', sa.Integer(), nullable=False),
    sa.Column('inicia_en', sa.DateTime(), nullable=True),
    sa.Column('termina_en', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'agotada', 'expirada', name='estadolicencia'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), server_default='MXN', nullable=False),
    sa.Column('referencia_paypal', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('pendiente', 'completado', 'fallido', 'cortesia', name='estadopago'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_curso_id'), 'pagos', ['curso_id'], unique=False)
    op.create_index(op.f('ix_pagos_referencia_paypal'), 'pagos', ['referencia_paypal'], unique=False)
    op.create_index(op.f('ix_pagos_usuario_id'), 'pagos', ['usuario_id'], unique=False)
    op.create_table('certificados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inscripcion_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('folio', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('url_pdf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hash_verificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emitido_en', sa.DateTime(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio'),
    sa.UniqueConstraint('inscripcion_id')
    )
    op.create_table('lecciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('modulo_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('video', 'quiz', 'lectura', name='tipoleccion'), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('duracion_seg', sa.Integer(), nullable=False),
    sa.Column('umbral_completado_pct', sa.Integer(), nullable=False),
    sa.Column('bunny_video_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hls_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votos_resena',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('calificacion_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('voto', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calificacion_id'], ['calificaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calificacion_id', 'usuario_id')
    )
    op.create_table('eventos_analytics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('leccion_id', sa.Uuid(), nullable=False),
    sa.Column('evento', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('posicion_seg', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['leccion_id'], ['lecciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progreso_lecciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inscripcion_id', sa.Uuid(), nullable=False),
    sa.Column('leccion_id', sa.Uuid(), nullable=False),
    sa.Column('visto_seg', sa.Integer(), nullable=False),
    sa.Column('progreso_pct', sa.Integer(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('completado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leccion_id'], ['lecciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inscripcion_id', 'leccion_id')
    )
    op.create_table('quiz_intentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inscripcion_id', sa.Uuid(), nullable=False),
    sa.Column('leccion_id', sa.Uuid(), nullable=False),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('total_preguntas', sa.Integer(), nullable=False),
    sa.Column('correctas', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leccion_id'], ['lecciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_intentos_inscripcion_leccion', 'quiz_intentos', ['inscripcion_id', 'leccion_id'], unique=False)
    op.create_table('recursos_leccion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('leccion_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('pdf', 'link', 'archivo', 'docx', 'xlsx', 'pptx', name='tiporecurso'), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leccion_id'], ['lecciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_respuestas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intento_id', sa.Uuid(), nullable=False),
    sa.Column('pregunta_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('opcion_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['intento_id'], ['quiz_intentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_respuestas')
    op.drop_table('recursos_leccion')
    op.drop_index('ix_quiz_intentos_inscripcion_leccion', table_name='quiz_intentos')
    op.drop_table('quiz_intentos')
    op.drop_table('progreso_lecciones')
    op.drop_table('eventos_analytics')
    op.drop_table('votos_resena')
    op.drop_table('lecciones')
    op.drop_table('certificados')
    op.drop_index(op.f('ix_pagos_usuario_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_referencia_paypal'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_curso_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_table('modulos')
    op.drop_table('licencias_curso')
    op.drop_index(op.f('ix_invitaciones_curso_token_hash'), table_name='invitaciones_curso')
    op.drop_index(op.f('ix_invitaciones_curso_email'), table_name='invitaciones_curso')
    op.drop_index(op.f('ix_invitaciones_curso_curso_id'), table_name='invitaciones_curso')
    op.drop_table('invitaciones_curso')
    op.drop_table('inscripciones')
    op.drop_table('curso_etiquetas')
    op.drop_table('comentarios_solicitud')
    op.drop_table('calificaciones')
    op.drop_table('usuarios_organizacion')
    op.drop_table('solicitudes_curso')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('notificaciones')
    op.drop_table('item')
    op.drop_table('eventos_sistema')
    op.drop_index(op.f('ix_cursos_slug'), table_name='cursos')
    op.drop_table('cursos')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('organizaciones')
    op.drop_index(op.f('ix_etiquetas_slug'), table_name='etiquetas')
    op.drop_table('etiquetas')
    op.drop_index(op.f('ix_categorias_slug'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
