"""add_all_domain_tables_and_extend_user

Revision ID: ad555931d588
Revises: 1a31ce608336
Create Date: 2026-02-26 14:09:31.987089

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad555931d588'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_slug'), 'categorias', ['slug'], unique=True)
    op.create_table('etiquetas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etiquetas_slug'), 'etiquetas', ['slug'], unique=True)
    op.create_table('organizaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rfc', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('dominio_corporativo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVA', 'INACTIVA', name='estadoorganizacion'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=False),
    sa.Column('instructor_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'REVISION', 'PUBLICADO', 'ARCHIVADO', name='estadocurso'), nullable=False),
    sa.Column('duracion_seg', sa.Integer(), nullable=False),
    sa.Column('calificacion_prom', sa.Float(), nullable=False),
    sa.Column('total_resenas', sa.Integer(), nullable=False),
    sa.Column('es_gratis', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('publicado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_slug'), 'cursos', ['slug'], unique=True)
    op.create_table('eventos_sistema',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('categoria', sa.Enum('AUTH', 'CRUD', 'ADMIN', 'SISTEMA', name='categoriaevento'), nullable=False),
    sa.Column('accion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entidad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('entidad_id', sa.Uuid(), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('canal', sa.Enum('EMAIL', 'WHATSAPP', 'PUSH', 'INAPP', name='canalnotificacion'), nullable=False),
    sa.Column('tipo', sa.Enum('INSCRIPCION', 'CERTIFICADO', 'SOLICITUD', 'SISTEMA', name='tiponotificacion'), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('cuerpo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ENVIADA', 'FALLIDA', 'LEIDA', name='estadonotificacion'), nullable=False),
    sa.Column('proveedor', sa.Enum('TWILIO', 'EMAIL', 'INTERNAL', name='proveedornotificacion'), nullable=True),
    sa.Column('proveedor_message_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.Column('leido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('revocado_en', sa.DateTime(), nullable=True),
    sa.Column('reemplazado_por_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_creacion', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_table('solicitudes_curso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizacion_id', sa.Uuid(), nullable=False),
    sa.Column('solicitante_id', sa.Uuid(), nullable=False),
    sa.Column('titulo_solicitud', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTA', 'EN_REVISION', 'APROBADA', 'RECHAZADA', 'CERRADA', name='estadosolicitud'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitante_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_organizacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizacion_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('rol_org', sa.Enum('MIEMBRO', 'ADMIN_ORG', name='rolorganizacion'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'usuario_id')
    )
    op.create_table('calificaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('estrellas', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('comentario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('PUBLICA', 'OCULTA', 'PENDIENTE', name='estadocalificacion'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'curso_id')
    )
    op.create_table('comentarios_solicitud',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('solicitud_id', sa.Uuid(), nullable=False),
    sa.Column('autor_id', sa.Uuid(), nullable=False),
    sa.Column('comentario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_curso.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso_etiquetas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('etiqueta_id', sa.Uuid(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiquetas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curso_id', 'etiqueta_id')
    )
    op.create_table('inscripciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'FINALIZADA', 'CANCELADO', name='estadoinscripcion'), nullable=False),
    sa.Column('inscrito_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acceso_en', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'curso_id')
    )
    op.create_table('licencias_curso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizacion_id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('cupos_total', sa.Integer(), nullable=False),
    sa.Column('cupos_usados', sa.Integer(), nullable=False),
    sa.Column('inicia_en', sa.DateTime(), nullable=True),
    sa.Column('termina_en', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVA', 'AGOTADA', 'EXPIRADA', name='estadolicencia'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inscripcion_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('folio', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('url_pdf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hash_verificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emitido_en', sa.DateTime(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio'),
    sa.UniqueConstraint('inscripcion_id')
    )
    op.create_table('lecciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('modulo_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('VIDEO', 'QUIZ', 'LECTURA', name='tipoleccion'), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('duracion_seg', sa.Integer(), nullable=False),
    sa.Column('umbral_completado_pct', sa.Integer(), nullable=False),
    sa.Column('bunny_video_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hls_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votos_resena',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('calificacion_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('voto', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calificacion_id'], ['calificaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calificacion_id', 'usuario_id')
    )
    op.create_table('eventos_analytics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('curso_id', sa.Uuid(), nullable=False),
    sa.Column('leccion_id', sa.Uuid(), nullable=False),
    sa.Column('evento', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('posicion_seg', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['leccion_id'], ['lecciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progreso_lecciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inscripcion_id', sa.Uuid(), nullable=False),
    sa.Column('leccion_id', sa.Uuid(), nullable=False),
    sa.Column('visto_seg', sa.Integer(), nullable=False),
    sa.Column('progreso_pct', sa.Integer(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('completado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leccion_id'], ['lecciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inscripcion_id', 'leccion_id')
    )
    op.create_table('recursos_leccion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('leccion_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('PDF', 'LINK', 'ARCHIVO', name='tiporecurso'), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leccion_id'], ['lecciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Create enum types first for user columns
    rolusuario = sa.Enum('ESTUDIANTE', 'INSTRUCTOR', 'USUARIO_CONTROL', 'ADMINISTRADOR', name='rolusuario')
    rolusuario.create(op.get_bind(), checkfirst=True)
    estadousuario = sa.Enum('ACTIVO', 'SUSPENDIDO', name='estadousuario')
    estadousuario.create(op.get_bind(), checkfirst=True)

    op.add_column('user', sa.Column('rol', rolusuario, nullable=False, server_default='ESTUDIANTE'))
    op.add_column('user', sa.Column('estado', estadousuario, nullable=False, server_default='ACTIVO'))
    op.add_column('user', sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('user', sa.Column('telefono_e164', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('user', sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user', sa.Column('notif_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notif_prefs')
    op.drop_column('user', 'whatsapp_opt_in')
    op.drop_column('user', 'telefono_e164')
    op.drop_column('user', 'telefono')
    op.drop_column('user', 'estado')
    op.drop_column('user', 'rol')
    op.drop_table('recursos_leccion')
    op.drop_table('progreso_lecciones')
    op.drop_table('eventos_analytics')
    op.drop_table('votos_resena')
    op.drop_table('lecciones')
    op.drop_table('certificados')
    op.drop_table('modulos')
    op.drop_table('licencias_curso')
    op.drop_table('inscripciones')
    op.drop_table('curso_etiquetas')
    op.drop_table('comentarios_solicitud')
    op.drop_table('calificaciones')
    op.drop_table('usuarios_organizacion')
    op.drop_table('solicitudes_curso')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('notificaciones')
    op.drop_table('eventos_sistema')
    op.drop_index(op.f('ix_cursos_slug'), table_name='cursos')
    op.drop_table('cursos')
    op.drop_table('organizaciones')
    op.drop_index(op.f('ix_etiquetas_slug'), table_name='etiquetas')
    op.drop_table('etiquetas')
    op.drop_index(op.f('ix_categorias_slug'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
